#!/bin/bash


Array_Core () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $ARRAY == "arraycore" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L0FycmF5Q29yZS9hcmNoaXZlL01haW4uemlw" | base64 -d
    elif [[ $ARRAY == "ARRAYCORE" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L0FycmF5Q29yZS9hcmNoaXZlL01haW4uemlw" | base64 -d
    elif [[ $ARRAY =~ $regex ]]
    then
        if [[ $ARRAY_BRANCH ]]
        then
            echo "${ARRAY}/archive/${ARRAY_BRANCH}.zip"
        else
            echo "${ARRAY}/archive/Main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L0FycmF5Q29yZS9hcmNoaXZlL01haW4uemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="arraycore.zip"
    echo "••• Downloading ArrayCore •••"
    wget -q $(Array_Core) -O "$zippath"
    echo "  Unpacking Data ..."
    VEMON=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    rm -rf "$zippath"
    sleep 5
    cd $VEMON
    echo "••• ArrayCore Here. •••"

    python3 ../raid/updater.py ../requirements.txt requirements.txt
    python3 -m ArrayCore
}

_set_bot
