#!/bin/bash


_raid_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL2Rlc2lub2JpdGEvQVJSQVlDT1JFLS9hcmNoaXZlL21haW4uemlw" | base64 -d
}


_starter () {
    local raidpath
    raidpath="arraycore.zip"
    echo "••• DOWNLOADING ArrayCore VcRaid •••"
    wget -q $(_raid_zip) -O "$raidpath"
    RAIDPATH=$(zipinfo -1 "$raidpath" | grep -v "/.");
    unzip -qq "$raidpath"
    rm -rf "$raidpath"
    cd $RAIDPATH
    python3 ../raid/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING ArrayCore VcRaid •••"
    python3 -m ArrayCore
}

_starter
