#!/bin/bash


_raid_repo () {
    local hrepo
    hrepo=`echo "" | base64 -d`
    echo "$rlink"
}

_raid_zip () {
    echo "" | base64 -d
}


_starter () {
    local raidpath
    raidpath="VcRaid.zip"
    echo "••• DOWNLOADING VcRaid •••"
    wget -q $(_raid_zip) -O "$raidpath"
    RAIDPATH=$(zipinfo -1 "$raidpath" | grep -v "/.");
    unzip -qq "$raidpath"
    rm -rf "$raidpath"
    cd $RAIDPATH
    python3 ../raid/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING VcRaid •••"
    python3 -m ArrayCore
}

_starter
